name: T5G2P

# Dataset info
train_dataset: ???
validation_dataset: ???

model:
  model_name: "t5-small"
  max_source_len: 150
  max_target_len: 730

  train_ds:
    dataset:
      #_target_: "nemo.collections.tts.data.datalayers.T5G2PDataset"
      manifest_filepath: ${train_dataset}
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 32 #32
      num_workers: 4

  validation_ds:
    dataset:
      #_target_: "nemo.collections.tts.data.datalayers.T5G2PDataset"
      manifest_filepath: ${validation_dataset}
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 32 #64
      num_workers: 4

  optim:
    name: adamw
    lr: 2e-4
    weight_decay: 0.01
    # scheduler setup
    sched:
      name: WarmupAnnealing

      # pytorch lightning args
      monitor: val_token_precision
      reduce_on_plateau: false

      # scheduler config override
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1

trainer:
  devices: 1 # number of gpus
  max_epochs: 5
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: 1
  enable_checkpointing: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 200
  check_val_every_n_epoch: 1

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    save_top_k: 3
    monitor: "val_per"
    mode: "min"
    save_best_model: true

